// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CCTVServerService.proto

package com.mingyan.smartClassroom.CCTVService;

public final class CCTVServiceProto {
  private CCTVServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mingyan_smartClassroom_VideoFrame_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mingyan_smartClassroom_VideoFrame_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mingyan_smartClassroom_StreamVideoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mingyan_smartClassroom_StreamVideoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027CCTVServerService.proto\022\032com.mingyan.s" +
      "martClassroom\"/\n\nVideoFrame\022\016\n\006number\030\001 " +
      "\001(\003\022\021\n\ttimestamp\030\002 \001(\003\"&\n\023StreamVideoRes" +
      "ponse\022\017\n\007message\030\001 \001(\t2\177\n\021CCTVServerServ" +
      "ice\022j\n\013StreamVideo\022&.com.mingyan.smartCl" +
      "assroom.VideoFrame\032/.com.mingyan.smartCl" +
      "assroom.StreamVideoResponse\"\000(\001B<\n&com.m" +
      "ingyan.smartClassroom.CCTVServiceB\020CCTVS" +
      "erviceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mingyan_smartClassroom_VideoFrame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mingyan_smartClassroom_VideoFrame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mingyan_smartClassroom_VideoFrame_descriptor,
        new java.lang.String[] { "Number", "Timestamp", });
    internal_static_com_mingyan_smartClassroom_StreamVideoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mingyan_smartClassroom_StreamVideoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mingyan_smartClassroom_StreamVideoResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
