// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CCTVServerService.proto

package com.mingyan.smartClassroom.CCTVService;

public interface StreamVideoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mingyan.smartClassroom.StreamVideoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A message or confirmation that the stream was received and processed
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * A message or confirmation that the stream was received and processed
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
