// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CCTVServerService.proto

package com.mingyan.smartClassroom.CCTVService;

public interface VideoFrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mingyan.smartClassroom.VideoFrame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * to simulate binary, I use random number instead.
   * </pre>
   *
   * <code>int64 number = 1;</code>
   */
  long getNumber();

  /**
   * <pre>
   * Timestamp for when the frame was captured
   * </pre>
   *
   * <code>int64 timestamp = 2;</code>
   */
  long getTimestamp();
}
