// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AttendanceServerService.proto

package com.mingyan.smartClassroom.attendanceTrackingService;

public interface AttendanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mingyan.smartClassroom.AttendanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
