// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AttendanceServerService.proto

package com.mingyan.smartClassroom.attendanceTrackingService;

public final class AttendanceTrackingServiceProto {
  private AttendanceTrackingServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mingyan_smartClassroom_AttendanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mingyan_smartClassroom_AttendanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mingyan_smartClassroom_AttendanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mingyan_smartClassroom_AttendanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mingyan_smartClassroom_StreamServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mingyan_smartClassroom_StreamServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mingyan_smartClassroom_StreamServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mingyan_smartClassroom_StreamServerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035AttendanceServerService.proto\022\032com.min" +
      "gyan.smartClassroom\"!\n\021AttendanceRequest" +
      "\022\014\n\004name\030\001 \001(\t\"%\n\022AttendanceResponse\022\017\n\007" +
      "message\030\001 \001(\t\")\n\023StreamServerRequest\022\022\n\n" +
      "serverName\030\001 \001(\t\"\'\n\024StreamServerResponse" +
      "\022\017\n\007message\030\001 \001(\t2\207\002\n\026StreamingServerSer" +
      "vice\022q\n\020sendUnaryRequest\022-.com.mingyan.s" +
      "martClassroom.AttendanceRequest\032..com.mi" +
      "ngyan.smartClassroom.AttendanceResponse\022" +
      "z\n\023streamServerRequest\022/.com.mingyan.sma" +
      "rtClassroom.StreamServerRequest\0320.com.mi" +
      "ngyan.smartClassroom.StreamServerRespons" +
      "e0\001BX\n4com.mingyan.smartClassroom.attend" +
      "anceTrackingServiceB\036AttendanceTrackingS" +
      "erviceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mingyan_smartClassroom_AttendanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mingyan_smartClassroom_AttendanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mingyan_smartClassroom_AttendanceRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_mingyan_smartClassroom_AttendanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mingyan_smartClassroom_AttendanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mingyan_smartClassroom_AttendanceResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_mingyan_smartClassroom_StreamServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_mingyan_smartClassroom_StreamServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mingyan_smartClassroom_StreamServerRequest_descriptor,
        new java.lang.String[] { "ServerName", });
    internal_static_com_mingyan_smartClassroom_StreamServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_mingyan_smartClassroom_StreamServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mingyan_smartClassroom_StreamServerResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
