// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AttendanceServerService.proto

package com.mingyan.smartClassroom.attendanceTrackingService;

public interface StreamServerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mingyan.smartClassroom.StreamServerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serverName = 1;</code>
   */
  java.lang.String getServerName();
  /**
   * <code>string serverName = 1;</code>
   */
  com.google.protobuf.ByteString
      getServerNameBytes();
}
