// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AttendanceServerService.proto

package com.mingyan.smartClassroom.attendanceTrackingService;

public interface StreamServerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mingyan.smartClassroom.StreamServerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
