// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatServerService.proto

package com.mingyan.smartClassroom.ChatService;

public final class ChatServiceProto {
  private ChatServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mingyan_smartClassroom_ClassroomMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mingyan_smartClassroom_ClassroomMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ChatServerService.proto\022\032com.mingyan.s" +
      "martClassroom\"D\n\020ClassroomMessage\022\014\n\004use" +
      "r\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\021\n\ttimestamp\030\003 " +
      "\001(\0032\207\001\n\024ClassroomInteraction\022o\n\013LiveSess" +
      "ion\022,.com.mingyan.smartClassroom.Classro" +
      "omMessage\032,.com.mingyan.smartClassroom.C" +
      "lassroomMessage\"\000(\0010\001B<\n&com.mingyan.sma" +
      "rtClassroom.ChatServiceB\020ChatServiceProt" +
      "oP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mingyan_smartClassroom_ClassroomMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mingyan_smartClassroom_ClassroomMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mingyan_smartClassroom_ClassroomMessage_descriptor,
        new java.lang.String[] { "User", "Message", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
