// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatServerService.proto

package com.mingyan.smartClassroom.ChatService;

public interface ClassroomMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mingyan.smartClassroom.ClassroomMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * could be 'teacher' or 'student_id'
   * </pre>
   *
   * <code>string user = 1;</code>
   */
  java.lang.String getUser();
  /**
   * <pre>
   * could be 'teacher' or 'student_id'
   * </pre>
   *
   * <code>string user = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <pre>
   * the message content
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * the message content
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * message timestamp
   * </pre>
   *
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();
}
